// Deterministic snapshot of application-owned objects of one database. Used by schema-snapshot.mjs and integration tests.
import pg from 'pg';

const EXCLUDED_SCHEMAS = ['pg_catalog', 'information_schema', 'pgboss'];

const NOT_EXT = (alias) => `NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.classid = 'pg_class'::regclass AND d.objid = ${alias}.oid AND d.deptype = 'e')`;

export async function snapshotDatabase(url) {
  const c = new pg.Client({ connectionString: url });
  await c.connect();
  try {
    const q = async (text, params = []) => (await c.query(text, params)).rows;
    const tables = await q(
      `SELECT c.oid, n.nspname AS schema, c.relname AS name
         FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind IN ('r','p') AND n.nspname <> ALL($1) AND n.nspname NOT LIKE 'pg\\_%' AND ${NOT_EXT('c')}
        ORDER BY n.nspname, c.relname`,
      [EXCLUDED_SCHEMAS],
    );
    const lines = [
      '-- BananaGig schema snapshot. GENERATED by scripts/schema-snapshot.mjs; do not edit by hand.',
      '-- Scope: application-owned objects only (excludes pgboss, PostGIS and other extension-owned objects, system catalogs).',
      '-- Regenerate: pnpm schema:snapshot --write',
      '',
    ];
    const schemas = [...new Set(tables.map((t) => t.schema))];
    for (const s of schemas.filter((x) => x !== 'public')) lines.push(`CREATE SCHEMA ${s};`);
    if (schemas.some((x) => x !== 'public')) lines.push('');
    if (!tables.length) lines.push('-- (no application tables)');
    for (const t of tables) {
      const cols = await q(
        `SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS type, a.attnotnull, pg_get_expr(d.adbin, d.adrelid) AS def, a.attidentity, a.attgenerated
           FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
          WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum`,
        [t.oid],
      );
      const cons = await q(
        `SELECT conname, pg_get_constraintdef(oid) AS def FROM pg_constraint WHERE conrelid = $1 AND contype IN ('p','f','u','c') ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 ELSE 3 END, conname`,
        [t.oid],
      );
      const idx = await q(
        `SELECT i.relname AS name, pg_get_indexdef(i.oid) AS def
           FROM pg_index x JOIN pg_class i ON i.oid = x.indexrelid
          WHERE x.indrelid = $1 AND NOT EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conindid = i.oid) ORDER BY i.relname`,
        [t.oid],
      );
      const colLines = cols.map((a) => {
        const gen = a.attidentity
          ? ` GENERATED ${a.attidentity === 'a' ? 'ALWAYS' : 'BY DEFAULT'} AS IDENTITY`
          : a.attgenerated
            ? ` GENERATED ALWAYS AS (${a.def}) STORED`
            : a.def
              ? ` DEFAULT ${a.def}`
              : '';
        return `  ${a.attname} ${a.type}${a.attnotnull ? ' NOT NULL' : ''}${gen}`;
      });
      const conLines = cons.map((k) => `  CONSTRAINT ${k.conname} ${k.def}`);
      lines.push(`CREATE TABLE ${t.schema}.${t.name} (`, [...colLines, ...conLines].join(',\n'), ');');
      for (const i of idx) lines.push(`${i.def};`);
      lines.push('');
    }
    return `${lines.join('\n').trimEnd()}\n`;
  } finally {
    await c.end();
  }
}
