// Generates docs/api/openapi.yaml (from the real Fastify route schemas) and docs/events/asyncapi.yaml
// (from the contracts event envelope). `--check` fails if the committed files drift from the code.
// Run through tsx: pnpm specs:generate | pnpm specs:check
import { readFileSync, writeFileSync } from 'node:fs';
import { stringify } from 'yaml';
import { z } from 'zod';
import { loadConfig } from '@bananagig/config';
import { EventEnvelope, INFRA_PING_EVENT_TYPE } from '@bananagig/contracts';
import { buildApp } from '../apps/api/src/app.ts';

const check = process.argv.includes('--check');
const header = (what) => `# GENERATED by scripts/generate-specs.mjs from ${what}. Do not edit by hand; run \`pnpm specs:generate\`.\n`;

const cfg = loadConfig({ service: 'bananagig-api', env: { NODE_ENV: 'test' } });
const app = await buildApp({ cfg, readiness: async () => ({}) });
await app.ready();
const openapi = app.swagger();
await app.close();

const { $schema: _a, ...envelopeSchema } = z.toJSONSchema(EventEnvelope, { target: 'draft-7' });
const asyncapi = {
  asyncapi: '3.0.0',
  info: {
    title: 'BananaGig Events',
    version: '1.0.0',
    description:
      'Event contract. Only the generic envelope and an infrastructure self-test event exist; product events arrive with their features. Subjects follow bananagig.<domain>.<event>.v<version>.',
  },
  defaultContentType: 'application/json',
  channels: {
    infraPing: {
      address: INFRA_PING_EVENT_TYPE,
      description: 'Infrastructure self-test used by the worker diagnostics. Not a product event.',
      messages: { infraPing: { $ref: '#/components/messages/EventEnvelope' } },
    },
  },
  operations: {
    receiveInfraPing: { action: 'receive', channel: { $ref: '#/channels/infraPing' }, summary: 'Worker consumes the infrastructure ping' },
  },
  components: {
    messages: {
      EventEnvelope: {
        name: 'EventEnvelope',
        title: 'Domain event envelope',
        headers: { type: 'object', properties: { 'x-correlation-id': { type: 'string' } } },
        payload: { $ref: '#/components/schemas/EventEnvelope' },
      },
    },
    schemas: { EventEnvelope: envelopeSchema },
  },
};

const outputs = [
  ['docs/api/openapi.yaml', header('apps/api route schemas + packages/contracts') + stringify(openapi, { lineWidth: 0 })],
  ['docs/events/asyncapi.yaml', header('packages/contracts EventEnvelope') + stringify(asyncapi, { lineWidth: 0 })],
];
let drift = false;
for (const [file, content] of outputs) {
  if (check) {
    let current = '';
    try {
      current = readFileSync(file, 'utf8');
    } catch {
      /* missing counts as drift */
    }
    if (current !== content) {
      console.error(`DRIFT: ${file} is out of date. Run pnpm specs:generate`);
      drift = true;
    }
  } else {
    writeFileSync(file, content);
    console.log(`wrote ${file}`);
  }
}
process.exit(drift ? 1 : 0);
