// Generates docs/api/openapi.yaml (from the real Fastify route schemas) and docs/events/asyncapi.yaml
// (from the contracts event envelope). `--check` fails if the committed files drift from the code.
// Run through tsx: pnpm specs:generate | pnpm specs:check
import { readFileSync, writeFileSync } from 'node:fs';
import { stringify } from 'yaml';
import { z } from 'zod';
import { loadConfig } from '@bananagig/config';
import {
  CONFIGURATION_EVENTS,
  CONTENT_EVENTS,
  ConfigurationEventPayload,
  ContentEventPayload,
  CountryEventPayload,
  EventEnvelope,
  GEOGRAPHY_EVENTS,
  INFRA_PING_EVENT_TYPE,
  LegalDocumentPublishedPayload,
  MarketEventPayload,
} from '@bananagig/contracts';
import { createTokenVerifier } from '@bananagig/identity';
import { buildApp } from '../apps/api/src/app.ts';

const check = process.argv.includes('--check');
const header = (what) => `# GENERATED by scripts/generate-specs.mjs from ${what}. Do not edit by hand; run \`pnpm specs:generate\`.\n`;

const cfg = loadConfig({ service: 'bananagig-api', env: { NODE_ENV: 'test' } });
// A verifier is required by buildApp but never used here (no requests are made); a static key resolver is enough.
const verifier = createTokenVerifier({
  issuer: cfg.identity.issuer,
  apiAudience: cfg.identity.apiAudience,
  jwks: async () => {
    throw new Error('not used');
  },
});
const app = await buildApp({ cfg, verifier, configuration: {}, content: {}, geography: {}, readiness: async () => ({}) });
await app.ready();
const openapi = app.swagger();
await app.close();

const { $schema: _a, ...envelopeSchema } = z.toJSONSchema(EventEnvelope, { target: 'draft-7' });
// Envelope with a fixed eventType and a typed payload, as JSON Schema (draft-07).
const typedEnvelope = (type, payload) => {
  const { $schema: _s, ...schema } = z.toJSONSchema(EventEnvelope.extend({ eventType: z.literal(type), payload }), { target: 'draft-7' });
  return schema;
};
const CONFIG_MESSAGES = {
  changeRequested: ['ConfigurationChangeRequested', 'A configuration change was submitted for approval.'],
  changeApproved: ['ConfigurationChangeApproved', 'A configuration change was approved (or auto-approved by policy NONE).'],
  changeRejected: ['ConfigurationChangeRejected', 'A configuration change was rejected.'],
  scheduled: ['ConfigurationScheduled', 'An approved change was published with a future effective time.'],
  activated: ['ConfigurationActivated', 'A configuration change became effective.'],
};
const CONTENT_MESSAGES = {
  versionApproved: ['ContentVersionApproved', 'A content version was approved (or auto-approved by policy NONE).', ContentEventPayload],
  versionScheduled: ['ContentVersionScheduled', 'An approved content version was published with a future effective time.', ContentEventPayload],
  versionPublished: [
    'ContentVersionPublished',
    'A content version became effective (immediately at publication or through the activation job); previousVersionId names the version it replaces.',
    ContentEventPayload,
  ],
  legalDocumentPublished: [
    'ContentLegalDocumentPublished',
    'A legal document version became effective (emitted in addition to ContentVersionPublished); bodySha256 lets consent records bind to the exact text.',
    LegalDocumentPublishedPayload,
  ],
};
const GEOGRAPHY_MESSAGES = {
  countryActivated: ['GeographyCountryActivated', 'A country became ACTIVE.', CountryEventPayload, 'geography_country'],
  countryDeactivated: [
    'GeographyCountryDeactivated',
    'An ACTIVE country was deactivated (ACTIVE to INACTIVE). Retiring a PLANNED country emits no event.',
    CountryEventPayload,
    'geography_country',
  ],
  marketCreated: ['GeographyMarketCreated', 'A market was created (PLANNED).', MarketEventPayload, 'geography_market'],
  marketActivated: ['GeographyMarketActivated', 'A market became ACTIVE.', MarketEventPayload, 'geography_market'],
  marketDeactivated: [
    'GeographyMarketDeactivated',
    'An ACTIVE market was deactivated (ACTIVE to INACTIVE). Retiring a PLANNED market emits no event.',
    MarketEventPayload,
    'geography_market',
  ],
  marketDefaultsChanged: [
    'GeographyMarketDefaultsChanged',
    'The defaults of a market changed: its default locale, currency or time zone (cause MARKET), or the distance unit, first day of week, date format or time format of its country (cause COUNTRY). changedFields names the fields, never their values.',
    MarketEventPayload,
    'geography_market',
  ],
};
const channels = {
  infraPing: {
    address: INFRA_PING_EVENT_TYPE,
    description: 'Infrastructure self-test used by the worker diagnostics. Not a product event.',
    messages: { infraPing: { $ref: '#/components/messages/EventEnvelope' } },
  },
};
const operations = { receiveInfraPing: { action: 'receive', channel: { $ref: '#/channels/infraPing' }, summary: 'Worker consumes the infrastructure ping' } };
const messages = {
  EventEnvelope: {
    name: 'EventEnvelope',
    title: 'Domain event envelope',
    headers: { type: 'object', properties: { 'x-correlation-id': { type: 'string' } } },
    payload: { $ref: '#/components/schemas/EventEnvelope' },
  },
};
const schemas = { EventEnvelope: envelopeSchema };
for (const [k, [name, summary]] of Object.entries(CONFIG_MESSAGES)) {
  const type = CONFIGURATION_EVENTS[k];
  channels[`configuration_${k}`] = {
    address: type,
    description: `${summary} Published through the transactional outbox; payload carries identifiers only, never values.`,
    messages: { [name]: { $ref: `#/components/messages/${name}` } },
  };
  operations[`send${name}`] = { action: 'send', channel: { $ref: `#/channels/configuration_${k}` }, summary };
  messages[name] = {
    name,
    title: summary,
    headers: { type: 'object', properties: { 'x-correlation-id': { type: 'string' } } },
    payload: { $ref: `#/components/schemas/${name}` },
  };
  schemas[name] = typedEnvelope(type, ConfigurationEventPayload);
}
for (const [k, [name, summary, payload]] of Object.entries(CONTENT_MESSAGES)) {
  const type = CONTENT_EVENTS[k];
  channels[`content_${k}`] = {
    address: type,
    description: `${summary} Published through the transactional outbox (aggregate content_version); payload carries identifiers and metadata only, never copy text.`,
    messages: { [name]: { $ref: `#/components/messages/${name}` } },
  };
  operations[`send${name}`] = { action: 'send', channel: { $ref: `#/channels/content_${k}` }, summary };
  messages[name] = {
    name,
    title: summary,
    headers: { type: 'object', properties: { 'x-correlation-id': { type: 'string' } } },
    payload: { $ref: `#/components/schemas/${name}` },
  };
  schemas[name] = typedEnvelope(type, payload);
}
for (const [k, [name, summary, payload, aggregate]] of Object.entries(GEOGRAPHY_MESSAGES)) {
  const type = GEOGRAPHY_EVENTS[k];
  channels[`geography_${k}`] = {
    address: type,
    description: `${summary} Published through the transactional outbox (aggregate ${aggregate}); payload carries identifiers only, never values.`,
    messages: { [name]: { $ref: `#/components/messages/${name}` } },
  };
  operations[`send${name}`] = { action: 'send', channel: { $ref: `#/channels/geography_${k}` }, summary };
  messages[name] = {
    name,
    title: summary,
    headers: { type: 'object', properties: { 'x-correlation-id': { type: 'string' } } },
    payload: { $ref: `#/components/schemas/${name}` },
  };
  schemas[name] = typedEnvelope(type, payload);
}
const asyncapi = {
  asyncapi: '3.0.0',
  info: {
    title: 'BananaGig Events',
    version: '1.0.0',
    description:
      'Event contract. The generic envelope, the infrastructure self-test event, the configuration registry events, the content registry events and the geography registry events exist; other product events arrive with their features. Subjects follow bananagig.<domain>.<event>.v<version>.',
  },
  defaultContentType: 'application/json',
  channels,
  operations,
  components: { messages, schemas },
};

const outputs = [
  ['docs/api/openapi.yaml', header('apps/api route schemas + packages/contracts') + stringify(openapi, { lineWidth: 0 })],
  ['docs/events/asyncapi.yaml', header('packages/contracts EventEnvelope') + stringify(asyncapi, { lineWidth: 0 })],
];
let drift = false;
for (const [file, content] of outputs) {
  if (check) {
    let current = '';
    try {
      current = readFileSync(file, 'utf8');
    } catch {
      /* missing counts as drift */
    }
    if (current !== content) {
      console.error(`DRIFT: ${file} is out of date. Run pnpm specs:generate`);
      drift = true;
    }
  } else {
    writeFileSync(file, content);
    console.log(`wrote ${file}`);
  }
}
process.exit(drift ? 1 : 0);
