global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus-metrics
    static_configs: [{ targets: ['localhost:9090'] }]
  - job_name: web-app
    static_configs: [{ targets: ['web-app:3000'] }]
  - job_name: api-service
    static_configs: [{ targets: ['api-service:3000'] }]
  - job_name: worker-service
    static_configs: [{ targets: ['worker-service:3000'] }]
