-- BananaGig schema snapshot. GENERATED by scripts/schema-snapshot.mjs; do not edit by hand.
-- Scope: application-owned objects only (excludes pgboss, PostGIS and other extension-owned objects, system catalogs).
-- Regenerate: pnpm schema:snapshot --write

CREATE SCHEMA configuration;
CREATE SCHEMA content;
CREATE SCHEMA geography;
CREATE SCHEMA identity;
CREATE SCHEMA integration;

CREATE TABLE configuration.audit_events (
  audit_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  actor text NOT NULL,
  action text NOT NULL,
  parameter_id uuid NOT NULL,
  change_request_id uuid,
  old_version_id uuid,
  new_version_id uuid,
  reason text,
  correlation_id text NOT NULL,
  CONSTRAINT pk_audit_events PRIMARY KEY (audit_event_id),
  CONSTRAINT fk_audit_events__change_request_id FOREIGN KEY (change_request_id) REFERENCES configuration.change_requests(change_request_id) ON DELETE RESTRICT,
  CONSTRAINT fk_audit_events__new_version_id FOREIGN KEY (new_version_id) REFERENCES configuration.value_versions(version_id) ON DELETE RESTRICT,
  CONSTRAINT fk_audit_events__old_version_id FOREIGN KEY (old_version_id) REFERENCES configuration.value_versions(version_id) ON DELETE RESTRICT,
  CONSTRAINT fk_audit_events__parameter_id FOREIGN KEY (parameter_id) REFERENCES configuration.parameters(parameter_id) ON DELETE RESTRICT,
  CONSTRAINT ck_audit_events__action CHECK ((action = ANY (ARRAY['PARAMETER_CREATED'::text, 'CHANGE_DRAFTED'::text, 'CHANGE_SUBMITTED'::text, 'CHANGE_APPROVED'::text, 'CHANGE_REJECTED'::text, 'CHANGE_CANCELLED'::text, 'CHANGE_PUBLISHED'::text, 'CHANGE_ACTIVATED'::text, 'CHANGE_SUPERSEDED'::text])))
);
CREATE INDEX idx_audit_events__change_request ON configuration.audit_events USING btree (change_request_id) WHERE (change_request_id IS NOT NULL);
CREATE INDEX idx_audit_events__parameter ON configuration.audit_events USING btree (parameter_id, occurred_at DESC);

CREATE TABLE configuration.change_approvals (
  approval_id uuid NOT NULL DEFAULT gen_random_uuid(),
  change_request_id uuid NOT NULL,
  approver text NOT NULL,
  decision text NOT NULL,
  comment text,
  decided_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_change_approvals PRIMARY KEY (approval_id),
  CONSTRAINT uq_change_approvals__request_approver UNIQUE (change_request_id, approver),
  CONSTRAINT fk_change_approvals__change_request_id FOREIGN KEY (change_request_id) REFERENCES configuration.change_requests(change_request_id) ON DELETE RESTRICT,
  CONSTRAINT ck_change_approvals__decision CHECK ((decision = ANY (ARRAY['APPROVE'::text, 'REJECT'::text])))
);

CREATE TABLE configuration.change_requests (
  change_request_id uuid NOT NULL DEFAULT gen_random_uuid(),
  parameter_id uuid NOT NULL,
  scope_type text NOT NULL,
  scope_ref text,
  proposed_value jsonb NOT NULL,
  effective_from timestamp with time zone NOT NULL,
  effective_to timestamp with time zone,
  reason text NOT NULL,
  requested_by text NOT NULL,
  approval_policy text NOT NULL,
  state text NOT NULL DEFAULT 'DRAFT'::text,
  value_version_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_change_requests PRIMARY KEY (change_request_id),
  CONSTRAINT uq_change_requests__value_version_id UNIQUE (value_version_id),
  CONSTRAINT fk_change_requests__parameter_scope FOREIGN KEY (parameter_id, scope_type) REFERENCES configuration.parameter_scopes(parameter_id, scope_type) ON DELETE RESTRICT,
  CONSTRAINT fk_change_requests__value_version_id FOREIGN KEY (value_version_id) REFERENCES configuration.value_versions(version_id) ON DELETE RESTRICT,
  CONSTRAINT ck_change_requests__approval_policy CHECK ((approval_policy = ANY (ARRAY['NONE'::text, 'OWNER_APPROVAL'::text, 'SECOND_APPROVER'::text]))),
  CONSTRAINT ck_change_requests__effective_range CHECK (((effective_to IS NULL) OR (effective_to > effective_from))),
  CONSTRAINT ck_change_requests__platform_has_no_ref CHECK (((scope_type = 'PLATFORM'::text) = (scope_ref IS NULL))),
  CONSTRAINT ck_change_requests__published_has_version CHECK (((state = ANY (ARRAY['SCHEDULED'::text, 'ACTIVE'::text, 'SUPERSEDED'::text])) = (value_version_id IS NOT NULL))),
  CONSTRAINT ck_change_requests__reason_not_blank CHECK ((length(btrim(reason)) > 0)),
  CONSTRAINT ck_change_requests__scope_ref_format CHECK (((scope_ref IS NULL) OR (scope_ref ~ '^[A-Za-z0-9._:-]{1,200}$'::text))),
  CONSTRAINT ck_change_requests__state CHECK ((state = ANY (ARRAY['DRAFT'::text, 'PENDING_APPROVAL'::text, 'APPROVED'::text, 'SCHEDULED'::text, 'ACTIVE'::text, 'REJECTED'::text, 'SUPERSEDED'::text, 'CANCELLED'::text])))
);
CREATE INDEX idx_change_requests__parameter ON configuration.change_requests USING btree (parameter_id, created_at DESC);
CREATE INDEX idx_change_requests__pending ON configuration.change_requests USING btree (created_at) WHERE (state = 'PENDING_APPROVAL'::text);
CREATE INDEX idx_change_requests__scheduled ON configuration.change_requests USING btree (effective_from) WHERE (state = 'SCHEDULED'::text);

CREATE TABLE configuration.parameter_scopes (
  parameter_id uuid NOT NULL,
  scope_type text NOT NULL,
  CONSTRAINT pk_parameter_scopes PRIMARY KEY (parameter_id, scope_type),
  CONSTRAINT fk_parameter_scopes__parameter_id FOREIGN KEY (parameter_id) REFERENCES configuration.parameters(parameter_id) ON DELETE RESTRICT,
  CONSTRAINT fk_parameter_scopes__scope_type FOREIGN KEY (scope_type) REFERENCES configuration.scope_levels(scope_type) ON DELETE RESTRICT
);

CREATE TABLE configuration.parameter_values (
  parameter_value_id uuid NOT NULL DEFAULT gen_random_uuid(),
  parameter_id uuid NOT NULL,
  scope_type text NOT NULL,
  scope_ref text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_parameter_values PRIMARY KEY (parameter_value_id),
  CONSTRAINT uq_parameter_values__parameter_scope_ref UNIQUE NULLS NOT DISTINCT (parameter_id, scope_type, scope_ref),
  CONSTRAINT fk_parameter_values__parameter_scope FOREIGN KEY (parameter_id, scope_type) REFERENCES configuration.parameter_scopes(parameter_id, scope_type) ON DELETE RESTRICT,
  CONSTRAINT ck_parameter_values__platform_has_no_ref CHECK (((scope_type = 'PLATFORM'::text) = (scope_ref IS NULL))),
  CONSTRAINT ck_parameter_values__scope_ref_format CHECK (((scope_ref IS NULL) OR (scope_ref ~ '^[A-Za-z0-9._:-]{1,200}$'::text)))
);

CREATE TABLE configuration.parameters (
  parameter_id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL,
  data_type text NOT NULL,
  unit text,
  description text NOT NULL,
  owner_role text NOT NULL,
  validation_rules jsonb NOT NULL DEFAULT '{}'::jsonb,
  sensitivity text NOT NULL DEFAULT 'INTERNAL'::text,
  approval_policy text NOT NULL,
  criticality text NOT NULL DEFAULT 'STANDARD'::text,
  is_required boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_parameters PRIMARY KEY (parameter_id),
  CONSTRAINT uq_parameters__key UNIQUE (key),
  CONSTRAINT ck_parameters__approval_policy CHECK ((approval_policy = ANY (ARRAY['NONE'::text, 'OWNER_APPROVAL'::text, 'SECOND_APPROVER'::text]))),
  CONSTRAINT ck_parameters__criticality CHECK ((criticality = ANY (ARRAY['STANDARD'::text, 'CRITICAL'::text]))),
  CONSTRAINT ck_parameters__data_type CHECK ((data_type = ANY (ARRAY['STRING'::text, 'INTEGER'::text, 'DECIMAL'::text, 'BOOLEAN'::text, 'ENUM'::text, 'DURATION'::text, 'MONEY'::text, 'JSON'::text]))),
  CONSTRAINT ck_parameters__description_not_blank CHECK ((length(btrim(description)) > 0)),
  CONSTRAINT ck_parameters__key_format CHECK (((key ~ '^[a-z][a-z0-9_]*([.][a-z][a-z0-9_]*)+$'::text) AND (length(key) <= 120))),
  CONSTRAINT ck_parameters__owner_role_format CHECK ((owner_role ~ '^[a-z][a-z0-9_-]*$'::text)),
  CONSTRAINT ck_parameters__sensitivity CHECK ((sensitivity = ANY (ARRAY['PUBLIC'::text, 'INTERNAL'::text, 'SENSITIVE'::text]))),
  CONSTRAINT ck_parameters__validation_rules_object CHECK ((jsonb_typeof(validation_rules) = 'object'::text))
);

CREATE TABLE configuration.scope_levels (
  scope_type text NOT NULL,
  rank smallint NOT NULL,
  CONSTRAINT pk_scope_levels PRIMARY KEY (scope_type),
  CONSTRAINT uq_scope_levels__rank UNIQUE (rank),
  CONSTRAINT ck_scope_levels__rank_nonnegative CHECK ((rank >= 0)),
  CONSTRAINT ck_scope_levels__scope_type_format CHECK ((scope_type ~ '^[A-Z][A-Z_]*$'::text))
);

CREATE TABLE configuration.snapshot_items (
  snapshot_id uuid NOT NULL,
  parameter_id uuid NOT NULL,
  version_id uuid NOT NULL,
  CONSTRAINT pk_snapshot_items PRIMARY KEY (snapshot_id, parameter_id),
  CONSTRAINT fk_snapshot_items__parameter_id FOREIGN KEY (parameter_id) REFERENCES configuration.parameters(parameter_id) ON DELETE RESTRICT,
  CONSTRAINT fk_snapshot_items__snapshot_id FOREIGN KEY (snapshot_id) REFERENCES configuration.snapshots(snapshot_id) ON DELETE RESTRICT,
  CONSTRAINT fk_snapshot_items__version_id FOREIGN KEY (version_id) REFERENCES configuration.value_versions(version_id) ON DELETE RESTRICT
);

CREATE TABLE configuration.snapshots (
  snapshot_id uuid NOT NULL DEFAULT gen_random_uuid(),
  evaluated_at timestamp with time zone NOT NULL,
  context jsonb NOT NULL,
  purpose text NOT NULL,
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_snapshots PRIMARY KEY (snapshot_id),
  CONSTRAINT ck_snapshots__context_object CHECK ((jsonb_typeof(context) = 'object'::text)),
  CONSTRAINT ck_snapshots__purpose_not_blank CHECK ((length(btrim(purpose)) > 0))
);

CREATE TABLE configuration.value_versions (
  version_id uuid NOT NULL DEFAULT gen_random_uuid(),
  parameter_value_id uuid NOT NULL,
  version integer NOT NULL,
  value jsonb NOT NULL,
  effective_from timestamp with time zone NOT NULL,
  effective_to timestamp with time zone,
  reason text NOT NULL,
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_value_versions PRIMARY KEY (version_id),
  CONSTRAINT uq_value_versions__parameter_value_version UNIQUE (parameter_value_id, version),
  CONSTRAINT fk_value_versions__parameter_value_id FOREIGN KEY (parameter_value_id) REFERENCES configuration.parameter_values(parameter_value_id) ON DELETE RESTRICT,
  CONSTRAINT ck_value_versions__effective_range CHECK (((effective_to IS NULL) OR (effective_to > effective_from))),
  CONSTRAINT ck_value_versions__reason_not_blank CHECK ((length(btrim(reason)) > 0)),
  CONSTRAINT ck_value_versions__version_positive CHECK ((version > 0))
);
CREATE INDEX idx_value_versions__holder_effective ON configuration.value_versions USING btree (parameter_value_id, effective_from DESC);

CREATE TABLE content.audit_events (
  audit_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  actor text NOT NULL,
  action text NOT NULL,
  entry_id uuid,
  locale text,
  version_id uuid,
  previous_version_id uuid,
  reason text,
  correlation_id text NOT NULL,
  CONSTRAINT pk_audit_events PRIMARY KEY (audit_event_id),
  CONSTRAINT fk_audit_events__entry_id FOREIGN KEY (entry_id) REFERENCES content.entries(entry_id) ON DELETE RESTRICT,
  CONSTRAINT fk_audit_events__previous_version_entry FOREIGN KEY (previous_version_id, entry_id) REFERENCES content.versions(version_id, entry_id) ON DELETE RESTRICT,
  CONSTRAINT fk_audit_events__version_entry FOREIGN KEY (version_id, entry_id) REFERENCES content.versions(version_id, entry_id) ON DELETE RESTRICT,
  CONSTRAINT ck_audit_events__action CHECK ((action = ANY (ARRAY['ENTRY_CREATED'::text, 'ENTRY_ACTIVATED'::text, 'ENTRY_DEACTIVATED'::text, 'LOCALE_REGISTERED'::text, 'LOCALE_ACTIVATED'::text, 'LOCALE_DEACTIVATED'::text, 'VERSION_DRAFTED'::text, 'VERSION_SUBMITTED'::text, 'VERSION_APPROVED'::text, 'VERSION_REJECTED'::text, 'VERSION_CANCELLED'::text, 'VERSION_PUBLISHED'::text, 'VERSION_ACTIVATED'::text, 'VERSION_SUPERSEDED'::text]))),
  CONSTRAINT ck_audit_events__subject CHECK ((((action ~~ 'LOCALE\_%'::text) AND (locale IS NOT NULL) AND (entry_id IS NULL) AND (version_id IS NULL) AND (previous_version_id IS NULL)) OR ((action ~~ 'ENTRY\_%'::text) AND (locale IS NULL) AND (entry_id IS NOT NULL) AND (version_id IS NULL) AND (previous_version_id IS NULL)) OR ((action ~~ 'VERSION\_%'::text) AND (locale IS NULL) AND (entry_id IS NOT NULL) AND (version_id IS NOT NULL))))
);
CREATE INDEX idx_audit_events__entry ON content.audit_events USING btree (entry_id, occurred_at DESC) WHERE (entry_id IS NOT NULL);
CREATE INDEX idx_audit_events__version ON content.audit_events USING btree (version_id) WHERE (version_id IS NOT NULL);

CREATE TABLE content.entries (
  entry_id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL,
  content_type text NOT NULL,
  owner_role text NOT NULL,
  description text NOT NULL,
  sensitivity text NOT NULL DEFAULT 'PUBLIC'::text,
  criticality text NOT NULL DEFAULT 'STANDARD'::text,
  approval_policy text NOT NULL,
  fallback_policy text NOT NULL DEFAULT 'CHAIN'::text,
  max_scope_type text NOT NULL DEFAULT 'PLATFORM'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_entries PRIMARY KEY (entry_id),
  CONSTRAINT uq_entries__key UNIQUE (key),
  CONSTRAINT fk_entries__max_scope_type FOREIGN KEY (max_scope_type) REFERENCES configuration.scope_levels(scope_type) ON DELETE RESTRICT,
  CONSTRAINT ck_entries__approval_policy CHECK ((approval_policy = ANY (ARRAY['NONE'::text, 'OWNER_APPROVAL'::text, 'SECOND_APPROVER'::text]))),
  CONSTRAINT ck_entries__content_type CHECK ((content_type = ANY (ARRAY['PLAIN_TEXT'::text, 'RICH_TEXT'::text, 'MARKDOWN'::text, 'EMAIL_SUBJECT'::text, 'EMAIL_BODY'::text, 'PUSH_TITLE'::text, 'PUSH_BODY'::text, 'LEGAL'::text, 'HELP_ARTICLE'::text, 'UI_LABEL'::text]))),
  CONSTRAINT ck_entries__criticality CHECK ((criticality = ANY (ARRAY['STANDARD'::text, 'CRITICAL'::text]))),
  CONSTRAINT ck_entries__description_not_blank CHECK ((length(btrim(description)) > 0)),
  CONSTRAINT ck_entries__fallback_policy CHECK ((fallback_policy = ANY (ARRAY['CHAIN'::text, 'LANGUAGE_ONLY'::text, 'EXACT'::text]))),
  CONSTRAINT ck_entries__key_format CHECK (((key ~ '^[a-z][a-z0-9_]*([.][a-z][a-z0-9_]*)+$'::text) AND (length(key) <= 160))),
  CONSTRAINT ck_entries__legal_policy CHECK (((content_type <> 'LEGAL'::text) OR ((owner_role = 'LEGAL'::text) AND (approval_policy = 'SECOND_APPROVER'::text) AND (criticality = 'CRITICAL'::text) AND (fallback_policy = 'EXACT'::text)))),
  CONSTRAINT ck_entries__max_scope_type CHECK ((max_scope_type = ANY (ARRAY['PLATFORM'::text, 'COUNTRY'::text, 'MARKET'::text]))),
  CONSTRAINT ck_entries__owner_role CHECK ((owner_role = ANY (ARRAY['CONTENT'::text, 'LEGAL'::text, 'SUPPORT'::text, 'MARKETING'::text]))),
  CONSTRAINT ck_entries__sensitivity CHECK ((sensitivity = ANY (ARRAY['PUBLIC'::text, 'INTERNAL'::text])))
);

CREATE TABLE content.entry_variables (
  entry_id uuid NOT NULL,
  name text NOT NULL,
  var_type text NOT NULL,
  is_required boolean NOT NULL DEFAULT true,
  description text NOT NULL,
  example_value jsonb NOT NULL,
  pii_class text NOT NULL DEFAULT 'NONE'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_entry_variables PRIMARY KEY (entry_id, name),
  CONSTRAINT fk_entry_variables__entry_id FOREIGN KEY (entry_id) REFERENCES content.entries(entry_id) ON DELETE RESTRICT,
  CONSTRAINT ck_entry_variables__description_not_blank CHECK ((length(btrim(description)) > 0)),
  CONSTRAINT ck_entry_variables__name_format CHECK (((name ~ '^[a-z][a-z0-9_]*$'::text) AND (length(name) <= 60))),
  CONSTRAINT ck_entry_variables__person_name_is_pii CHECK (((var_type <> 'PERSON_DISPLAY_NAME'::text) OR (pii_class <> 'NONE'::text))),
  CONSTRAINT ck_entry_variables__pii_class CHECK ((pii_class = ANY (ARRAY['NONE'::text, 'PERSONAL'::text, 'SENSITIVE_PERSONAL'::text]))),
  CONSTRAINT ck_entry_variables__var_type CHECK ((var_type = ANY (ARRAY['STRING'::text, 'NUMBER'::text, 'MONEY'::text, 'DATE'::text, 'TIME'::text, 'DATETIME'::text, 'URL'::text, 'PERSON_DISPLAY_NAME'::text, 'COUNT'::text])))
);

CREATE TABLE content.locales (
  locale text NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  is_platform_default boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  display_name text NOT NULL,
  language text GENERATED ALWAYS AS (split_part(locale, '-'::text, 1)) STORED,
  script text GENERATED ALWAYS AS ("substring"(locale, '^[a-z]{2,3}-([A-Z][a-z]{3})'::text)) STORED,
  region text GENERATED ALWAYS AS ("substring"(locale, '-([A-Z]{2}|[0-9]{3})$'::text)) STORED,
  CONSTRAINT pk_locales PRIMARY KEY (locale),
  CONSTRAINT ck_locales__bcp47_format CHECK ((locale ~ '^[a-z]{2,3}(-[A-Z][a-z]{3})?(-([A-Z]{2}|[0-9]{3}))?$'::text)),
  CONSTRAINT ck_locales__default_is_active CHECK (((NOT is_platform_default) OR is_active)),
  CONSTRAINT ck_locales__display_name_not_blank CHECK ((length(btrim(display_name)) > 0))
);
CREATE UNIQUE INDEX uq_locales__platform_default ON content.locales USING btree (is_platform_default) WHERE is_platform_default;

CREATE TABLE content.snapshot_items (
  snapshot_id uuid NOT NULL,
  entry_id uuid NOT NULL,
  version_id uuid NOT NULL,
  CONSTRAINT pk_snapshot_items PRIMARY KEY (snapshot_id, entry_id),
  CONSTRAINT fk_snapshot_items__entry_version FOREIGN KEY (version_id, entry_id) REFERENCES content.versions(version_id, entry_id) ON DELETE RESTRICT,
  CONSTRAINT fk_snapshot_items__snapshot_id FOREIGN KEY (snapshot_id) REFERENCES content.snapshots(snapshot_id) ON DELETE RESTRICT
);

CREATE TABLE content.snapshots (
  snapshot_id uuid NOT NULL DEFAULT gen_random_uuid(),
  evaluated_at timestamp with time zone NOT NULL,
  requested_locale text NOT NULL,
  context jsonb NOT NULL,
  purpose text NOT NULL,
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_snapshots PRIMARY KEY (snapshot_id),
  CONSTRAINT ck_snapshots__context_object CHECK ((jsonb_typeof(context) = 'object'::text)),
  CONSTRAINT ck_snapshots__locale_format CHECK ((requested_locale ~ '^[a-z]{2,3}(-[A-Z][a-z]{3})?(-([A-Z]{2}|[0-9]{3}))?$'::text)),
  CONSTRAINT ck_snapshots__purpose_not_blank CHECK ((length(btrim(purpose)) > 0))
);

CREATE TABLE content.version_approvals (
  approval_id uuid NOT NULL DEFAULT gen_random_uuid(),
  version_id uuid NOT NULL,
  approver text NOT NULL,
  decision text NOT NULL,
  comment text,
  decided_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_version_approvals PRIMARY KEY (approval_id),
  CONSTRAINT uq_version_approvals__version_approver UNIQUE (version_id, approver),
  CONSTRAINT fk_version_approvals__version_id FOREIGN KEY (version_id) REFERENCES content.versions(version_id) ON DELETE RESTRICT,
  CONSTRAINT ck_version_approvals__decision CHECK ((decision = ANY (ARRAY['APPROVE'::text, 'REJECT'::text])))
);

CREATE TABLE content.versions (
  version_id uuid NOT NULL DEFAULT gen_random_uuid(),
  entry_id uuid NOT NULL,
  locale text NOT NULL,
  scope_type text NOT NULL DEFAULT 'PLATFORM'::text,
  scope_ref text,
  version integer NOT NULL,
  body text NOT NULL,
  body_sha256 text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'DRAFT'::text,
  approval_policy text NOT NULL,
  effective_from timestamp with time zone NOT NULL,
  effective_to timestamp with time zone,
  reason text NOT NULL,
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_versions PRIMARY KEY (version_id),
  CONSTRAINT uq_versions__holder_version UNIQUE NULLS NOT DISTINCT (entry_id, locale, scope_type, scope_ref, version),
  CONSTRAINT uq_versions__version_entry UNIQUE (version_id, entry_id),
  CONSTRAINT fk_versions__entry_id FOREIGN KEY (entry_id) REFERENCES content.entries(entry_id) ON DELETE RESTRICT,
  CONSTRAINT fk_versions__locale FOREIGN KEY (locale) REFERENCES content.locales(locale) ON DELETE RESTRICT,
  CONSTRAINT fk_versions__scope_type FOREIGN KEY (scope_type) REFERENCES configuration.scope_levels(scope_type) ON DELETE RESTRICT,
  CONSTRAINT ck_versions__approval_policy CHECK ((approval_policy = ANY (ARRAY['NONE'::text, 'OWNER_APPROVAL'::text, 'SECOND_APPROVER'::text]))),
  CONSTRAINT ck_versions__body_length CHECK (((length(body) >= 1) AND (length(body) <= 200000))),
  CONSTRAINT ck_versions__effective_range CHECK (((effective_to IS NULL) OR (effective_to > effective_from))),
  CONSTRAINT ck_versions__platform_has_no_ref CHECK (((scope_type = 'PLATFORM'::text) = (scope_ref IS NULL))),
  CONSTRAINT ck_versions__reason_not_blank CHECK ((length(btrim(reason)) > 0)),
  CONSTRAINT ck_versions__scope_ref_format CHECK (((scope_ref IS NULL) OR (scope_ref ~ '^[A-Za-z0-9._:-]{1,200}$'::text))),
  CONSTRAINT ck_versions__scope_type CHECK ((scope_type = ANY (ARRAY['PLATFORM'::text, 'COUNTRY'::text, 'MARKET'::text]))),
  CONSTRAINT ck_versions__status CHECK ((status = ANY (ARRAY['DRAFT'::text, 'IN_REVIEW'::text, 'APPROVED'::text, 'SCHEDULED'::text, 'PUBLISHED'::text, 'SUPERSEDED'::text, 'REJECTED'::text, 'CANCELLED'::text]))),
  CONSTRAINT ck_versions__version_positive CHECK ((version > 0))
);
CREATE INDEX idx_versions__entry ON content.versions USING btree (entry_id, created_at DESC);
CREATE INDEX idx_versions__in_review ON content.versions USING btree (created_at) WHERE (status = 'IN_REVIEW'::text);
CREATE INDEX idx_versions__resolution ON content.versions USING btree (entry_id, locale, scope_type, effective_from DESC) WHERE (status = ANY (ARRAY['SCHEDULED'::text, 'PUBLISHED'::text, 'SUPERSEDED'::text]));
CREATE INDEX idx_versions__scheduled ON content.versions USING btree (effective_from) WHERE (status = 'SCHEDULED'::text);

CREATE TABLE geography.address_format_fields (
  address_format_id uuid NOT NULL,
  field_type text NOT NULL,
  display_order smallint NOT NULL,
  content_label_key text NOT NULL,
  required boolean NOT NULL,
  max_length smallint NOT NULL,
  input_type text NOT NULL DEFAULT 'TEXT'::text,
  validation_pattern text,
  example_value text,
  autocomplete_hint text,
  normalization_rule text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_address_format_fields PRIMARY KEY (address_format_id, field_type),
  CONSTRAINT uq_address_format_fields__format_order UNIQUE (address_format_id, display_order),
  CONSTRAINT fk_address_format_fields__format FOREIGN KEY (address_format_id) REFERENCES geography.address_formats(address_format_id) ON DELETE RESTRICT,
  CONSTRAINT fk_address_format_fields__label_key FOREIGN KEY (content_label_key) REFERENCES content.entries(key) ON DELETE RESTRICT,
  CONSTRAINT ck_address_format_fields__autocomplete_hint CHECK (((autocomplete_hint IS NULL) OR (autocomplete_hint ~ '^[a-z][a-z0-9-]{0,39}$'::text))),
  CONSTRAINT ck_address_format_fields__display_order CHECK (((display_order >= 1) AND (display_order <= 20))),
  CONSTRAINT ck_address_format_fields__example CHECK (((example_value IS NULL) OR ((length(btrim(example_value)) > 0) AND (length(example_value) <= 100) AND (example_value !~ '[\u0000-\u001F\u007F]'::text)))),
  CONSTRAINT ck_address_format_fields__field_type CHECK ((field_type = ANY (ARRAY['ORGANIZATION'::text, 'ADDRESS_LINE_1'::text, 'ADDRESS_LINE_2'::text, 'DEPENDENT_LOCALITY'::text, 'LOCALITY'::text, 'ADMINISTRATIVE_AREA'::text, 'POSTAL_CODE'::text, 'SORTING_CODE'::text]))),
  CONSTRAINT ck_address_format_fields__input_type CHECK ((input_type = ANY (ARRAY['TEXT'::text, 'LOOKUP'::text]))),
  CONSTRAINT ck_address_format_fields__label_key_format CHECK ((content_label_key ~ '^[a-z][a-z0-9_]*([.][a-z][a-z0-9_]*)+$'::text)),
  CONSTRAINT ck_address_format_fields__lookup_has_no_pattern CHECK (((input_type = 'TEXT'::text) OR ((validation_pattern IS NULL) AND (normalization_rule IS NULL)))),
  CONSTRAINT ck_address_format_fields__lookup_only_for_area CHECK (((input_type = 'TEXT'::text) OR (field_type = 'ADMINISTRATIVE_AREA'::text))),
  CONSTRAINT ck_address_format_fields__max_length CHECK (((max_length >= 1) AND (max_length <= 200))),
  CONSTRAINT ck_address_format_fields__normalization_rule CHECK (((normalization_rule IS NULL) OR (normalization_rule = ANY (ARRAY['UPPERCASE'::text, 'REMOVE_SPACES'::text, 'UPPERCASE_REMOVE_SPACES'::text])))),
  CONSTRAINT ck_address_format_fields__pattern_length CHECK (((validation_pattern IS NULL) OR ((length(validation_pattern) >= 1) AND (length(validation_pattern) <= 200))))
);

CREATE TABLE geography.address_formats (
  address_format_id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_id uuid NOT NULL,
  version integer NOT NULL,
  status text NOT NULL DEFAULT 'DRAFT'::text,
  display_template text NOT NULL,
  effective_from timestamp with time zone NOT NULL,
  effective_to timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_address_formats PRIMARY KEY (address_format_id),
  CONSTRAINT uq_address_formats__country_version UNIQUE (country_id, version),
  CONSTRAINT uq_address_formats__format_country UNIQUE (address_format_id, country_id),
  CONSTRAINT fk_address_formats__country_id FOREIGN KEY (country_id) REFERENCES geography.countries(country_id) ON DELETE RESTRICT,
  CONSTRAINT ck_address_formats__draft_is_open CHECK (((status <> 'DRAFT'::text) OR (effective_to IS NULL))),
  CONSTRAINT ck_address_formats__effective_range CHECK (((effective_to IS NULL) OR (effective_to > effective_from))),
  CONSTRAINT ck_address_formats__status CHECK ((status = ANY (ARRAY['DRAFT'::text, 'PUBLISHED'::text]))),
  CONSTRAINT ck_address_formats__template CHECK ((((length(display_template) >= 1) AND (length(display_template) <= 500)) AND (display_template !~ '[\u0001-\u0009\u000B-\u001F\u007F]'::text))),
  CONSTRAINT ck_address_formats__version CHECK ((version >= 1))
);

CREATE TABLE geography.addresses (
  address_id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_id uuid NOT NULL,
  address_format_id uuid NOT NULL,
  administrative_area_id uuid,
  administrative_area_code text,
  administrative_area_name text,
  organization text,
  address_line_1 text NOT NULL,
  address_line_2 text,
  dependent_locality text,
  locality text,
  postal_code text,
  sorting_code text,
  location geography(Point,4326),
  time_zone_id uuid,
  formatted_address text NOT NULL,
  validation_status text NOT NULL,
  validation_source text NOT NULL,
  provider_code text,
  provider_reference text,
  raw_input jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_addresses PRIMARY KEY (address_id),
  CONSTRAINT fk_addresses__area_country_code FOREIGN KEY (administrative_area_id, country_id, administrative_area_code) REFERENCES geography.administrative_areas(administrative_area_id, country_id, code) ON DELETE RESTRICT,
  CONSTRAINT fk_addresses__country_id FOREIGN KEY (country_id) REFERENCES geography.countries(country_id) ON DELETE RESTRICT,
  CONSTRAINT fk_addresses__format_country FOREIGN KEY (address_format_id, country_id) REFERENCES geography.address_formats(address_format_id, country_id) ON DELETE RESTRICT,
  CONSTRAINT fk_addresses__time_zone_id FOREIGN KEY (time_zone_id) REFERENCES geography.time_zones(time_zone_id) ON DELETE RESTRICT,
  CONSTRAINT ck_addresses__area_consistent CHECK ((((administrative_area_id IS NULL) = (administrative_area_code IS NULL)) AND ((administrative_area_code IS NULL) OR (administrative_area_name IS NOT NULL)))),
  CONSTRAINT ck_addresses__autocomplete_is_not_verified CHECK (((validation_source <> 'AUTOCOMPLETE'::text) OR (validation_status = ANY (ARRAY['UNVERIFIED'::text, 'FORMAT_VALID'::text, 'INVALID'::text])))),
  CONSTRAINT ck_addresses__formatted_address CHECK (((length(btrim(formatted_address)) > 0) AND (length(formatted_address) <= 1500))),
  CONSTRAINT ck_addresses__located_status_has_location CHECK (((validation_status <> ALL (ARRAY['GEOCODED'::text, 'VERIFIED'::text])) OR (location IS NOT NULL))),
  CONSTRAINT ck_addresses__manual_is_not_located CHECK (((validation_source <> 'MANUAL'::text) OR ((location IS NULL) AND (validation_status = ANY (ARRAY['UNVERIFIED'::text, 'FORMAT_VALID'::text, 'INVALID'::text]))))),
  CONSTRAINT ck_addresses__provider CHECK ((((validation_source = ANY (ARRAY['AUTOCOMPLETE'::text, 'GEOCODER'::text])) = (provider_code IS NOT NULL)) OR (validation_source = 'IMPORTED'::text))),
  CONSTRAINT ck_addresses__provider_code_format CHECK (((provider_code IS NULL) OR (provider_code ~ '^[a-z][a-z0-9_-]{1,39}$'::text))),
  CONSTRAINT ck_addresses__provider_reference CHECK (((provider_reference IS NULL) OR ((provider_code IS NOT NULL) AND (length(btrim(provider_reference)) > 0) AND (length(provider_reference) <= 200) AND (provider_reference !~ '[\u0000-\u001F\u007F]'::text)))),
  CONSTRAINT ck_addresses__raw_input CHECK (((jsonb_typeof(raw_input) = 'object'::text) AND (length((raw_input)::text) <= 4000))),
  CONSTRAINT ck_addresses__text_values CHECK (((length(btrim(address_line_1)) > 0) AND (length(address_line_1) <= 200) AND ((organization IS NULL) OR ((length(btrim(organization)) > 0) AND (length(organization) <= 200))) AND ((address_line_2 IS NULL) OR ((length(btrim(address_line_2)) > 0) AND (length(address_line_2) <= 200))) AND ((dependent_locality IS NULL) OR ((length(btrim(dependent_locality)) > 0) AND (length(dependent_locality) <= 200))) AND ((locality IS NULL) OR ((length(btrim(locality)) > 0) AND (length(locality) <= 200))) AND ((administrative_area_name IS NULL) OR ((length(btrim(administrative_area_name)) > 0) AND (length(administrative_area_name) <= 200))) AND ((postal_code IS NULL) OR ((length(btrim(postal_code)) > 0) AND (length(postal_code) <= 200))) AND ((sorting_code IS NULL) OR ((length(btrim(sorting_code)) > 0) AND (length(sorting_code) <= 200))))),
  CONSTRAINT ck_addresses__validation_source CHECK ((validation_source = ANY (ARRAY['MANUAL'::text, 'AUTOCOMPLETE'::text, 'GEOCODER'::text, 'ADMIN'::text, 'IMPORTED'::text]))),
  CONSTRAINT ck_addresses__validation_status CHECK ((validation_status = ANY (ARRAY['UNVERIFIED'::text, 'FORMAT_VALID'::text, 'GEOCODED'::text, 'VERIFIED'::text, 'INVALID'::text]))),
  CONSTRAINT ck_addresses__verified_source CHECK (((validation_status <> 'VERIFIED'::text) OR (validation_source = ANY (ARRAY['GEOCODER'::text, 'ADMIN'::text]))))
);

CREATE TABLE geography.administrative_areas (
  administrative_area_id uuid NOT NULL DEFAULT gen_random_uuid(),
  country_id uuid NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  area_type text NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE'::text,
  parent_area_id uuid,
  display_order integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_administrative_areas PRIMARY KEY (administrative_area_id),
  CONSTRAINT uq_administrative_areas__area_country UNIQUE (administrative_area_id, country_id),
  CONSTRAINT uq_administrative_areas__area_country_code UNIQUE (administrative_area_id, country_id, code),
  CONSTRAINT uq_administrative_areas__country_code UNIQUE (country_id, code),
  CONSTRAINT fk_administrative_areas__country_id FOREIGN KEY (country_id) REFERENCES geography.countries(country_id) ON DELETE RESTRICT,
  CONSTRAINT fk_administrative_areas__parent FOREIGN KEY (parent_area_id, country_id) REFERENCES geography.administrative_areas(administrative_area_id, country_id) ON DELETE RESTRICT,
  CONSTRAINT ck_administrative_areas__area_type CHECK ((area_type = ANY (ARRAY['STATE'::text, 'PROVINCE'::text, 'TERRITORY'::text, 'DISTRICT'::text, 'REGION'::text, 'COUNTY'::text, 'OTHER'::text]))),
  CONSTRAINT ck_administrative_areas__code_format CHECK ((code ~ '^[A-Z0-9][A-Z0-9-]{0,9}$'::text)),
  CONSTRAINT ck_administrative_areas__display_order CHECK (((display_order IS NULL) OR (display_order >= 0))),
  CONSTRAINT ck_administrative_areas__name_not_blank CHECK (((length(btrim(name)) > 0) AND (length(name) <= 120))),
  CONSTRAINT ck_administrative_areas__not_own_parent CHECK (((parent_area_id IS NULL) OR (parent_area_id <> administrative_area_id))),
  CONSTRAINT ck_administrative_areas__status CHECK ((status = ANY (ARRAY['ACTIVE'::text, 'INACTIVE'::text])))
);

CREATE TABLE geography.audit_events (
  audit_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  occurred_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  actor text NOT NULL,
  action text NOT NULL,
  country_id uuid,
  market_id uuid,
  changes jsonb,
  reason text,
  correlation_id text NOT NULL,
  address_format_id uuid,
  CONSTRAINT pk_audit_events PRIMARY KEY (audit_event_id),
  CONSTRAINT fk_audit_events__address_format_id FOREIGN KEY (address_format_id) REFERENCES geography.address_formats(address_format_id) ON DELETE RESTRICT,
  CONSTRAINT fk_audit_events__country_id FOREIGN KEY (country_id) REFERENCES geography.countries(country_id) ON DELETE RESTRICT,
  CONSTRAINT fk_audit_events__market_id FOREIGN KEY (market_id) REFERENCES geography.markets(market_id) ON DELETE RESTRICT,
  CONSTRAINT ck_audit_events__action CHECK ((action = ANY (ARRAY['COUNTRY_CREATED'::text, 'COUNTRY_UPDATED'::text, 'COUNTRY_ACTIVATED'::text, 'COUNTRY_DEACTIVATED'::text, 'MARKET_CREATED'::text, 'MARKET_UPDATED'::text, 'MARKET_ACTIVATED'::text, 'MARKET_DEACTIVATED'::text, 'COUNTRY_ADMINISTRATIVE_AREAS_UPDATED'::text, 'ADDRESS_FORMAT_DRAFTED'::text, 'ADDRESS_FORMAT_PUBLISHED'::text]))),
  CONSTRAINT ck_audit_events__changes_object CHECK (((changes IS NULL) OR (jsonb_typeof(changes) = 'object'::text))),
  CONSTRAINT ck_audit_events__subject CHECK ((((action ~~ 'COUNTRY\_%'::text) AND (country_id IS NOT NULL) AND (market_id IS NULL) AND (address_format_id IS NULL)) OR ((action ~~ 'MARKET\_%'::text) AND (market_id IS NOT NULL) AND (country_id IS NULL) AND (address_format_id IS NULL)) OR ((action ~~ 'ADDRESS\_FORMAT\_%'::text) AND (address_format_id IS NOT NULL) AND (country_id IS NULL) AND (market_id IS NULL))))
);
CREATE INDEX idx_audit_events__address_format ON geography.audit_events USING btree (address_format_id, occurred_at DESC) WHERE (address_format_id IS NOT NULL);
CREATE INDEX idx_audit_events__country ON geography.audit_events USING btree (country_id, occurred_at DESC) WHERE (country_id IS NOT NULL);
CREATE INDEX idx_audit_events__market ON geography.audit_events USING btree (market_id, occurred_at DESC) WHERE (market_id IS NOT NULL);

CREATE TABLE geography.countries (
  country_id uuid NOT NULL DEFAULT gen_random_uuid(),
  iso_alpha2 character(2) NOT NULL,
  iso_alpha3 character(3) NOT NULL,
  iso_numeric character(3) NOT NULL,
  display_name_content_key text NOT NULL,
  status text NOT NULL DEFAULT 'PLANNED'::text,
  dialing_code text NOT NULL,
  default_currency_code character(3) NOT NULL,
  default_locale text NOT NULL,
  distance_unit text NOT NULL,
  first_day_of_week text NOT NULL,
  date_format_code text NOT NULL,
  time_format_code text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_countries PRIMARY KEY (country_id),
  CONSTRAINT uq_countries__iso_alpha2 UNIQUE (iso_alpha2),
  CONSTRAINT uq_countries__iso_alpha3 UNIQUE (iso_alpha3),
  CONSTRAINT uq_countries__iso_numeric UNIQUE (iso_numeric),
  CONSTRAINT fk_countries__default_currency_code FOREIGN KEY (default_currency_code) REFERENCES geography.currencies(currency_code) ON DELETE RESTRICT,
  CONSTRAINT fk_countries__default_locale FOREIGN KEY (country_id, default_locale) REFERENCES geography.country_locales(country_id, locale) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT fk_countries__display_name_content_key FOREIGN KEY (display_name_content_key) REFERENCES content.entries(key) ON DELETE RESTRICT,
  CONSTRAINT ck_countries__content_key_format CHECK ((display_name_content_key ~ '^[a-z][a-z0-9_]*([.][a-z][a-z0-9_]*)+$'::text)),
  CONSTRAINT ck_countries__date_format_code CHECK ((date_format_code = ANY (ARRAY['MDY'::text, 'DMY'::text, 'YMD'::text]))),
  CONSTRAINT ck_countries__dialing_code_format CHECK ((dialing_code ~ '^[+][0-9]{1,4}$'::text)),
  CONSTRAINT ck_countries__distance_unit CHECK ((distance_unit = ANY (ARRAY['MILES'::text, 'KILOMETERS'::text]))),
  CONSTRAINT ck_countries__first_day_of_week CHECK ((first_day_of_week = ANY (ARRAY['MONDAY'::text, 'TUESDAY'::text, 'WEDNESDAY'::text, 'THURSDAY'::text, 'FRIDAY'::text, 'SATURDAY'::text, 'SUNDAY'::text]))),
  CONSTRAINT ck_countries__iso_alpha2_format CHECK ((iso_alpha2 ~ '^[A-Z]{2}$'::text)),
  CONSTRAINT ck_countries__iso_alpha3_format CHECK ((iso_alpha3 ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT ck_countries__iso_numeric_format CHECK ((iso_numeric ~ '^[0-9]{3}$'::text)),
  CONSTRAINT ck_countries__status CHECK ((status = ANY (ARRAY['PLANNED'::text, 'ACTIVE'::text, 'INACTIVE'::text]))),
  CONSTRAINT ck_countries__time_format_code CHECK ((time_format_code = ANY (ARRAY['12_HOUR'::text, '24_HOUR'::text])))
);
CREATE INDEX idx_countries__active ON geography.countries USING btree (iso_alpha2) WHERE (status = 'ACTIVE'::text);

CREATE TABLE geography.country_locales (
  country_id uuid NOT NULL,
  locale text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_country_locales PRIMARY KEY (country_id, locale),
  CONSTRAINT fk_country_locales__country_id FOREIGN KEY (country_id) REFERENCES geography.countries(country_id) ON DELETE RESTRICT,
  CONSTRAINT fk_country_locales__locale FOREIGN KEY (locale) REFERENCES content.locales(locale) ON DELETE RESTRICT
);

CREATE TABLE geography.country_time_zones (
  country_id uuid NOT NULL,
  time_zone_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_country_time_zones PRIMARY KEY (country_id, time_zone_id),
  CONSTRAINT fk_country_time_zones__country_id FOREIGN KEY (country_id) REFERENCES geography.countries(country_id) ON DELETE RESTRICT,
  CONSTRAINT fk_country_time_zones__time_zone_id FOREIGN KEY (time_zone_id) REFERENCES geography.time_zones(time_zone_id) ON DELETE RESTRICT
);

CREATE TABLE geography.currencies (
  currency_code character(3) NOT NULL,
  numeric_code character(3) NOT NULL,
  minor_unit_digits smallint NOT NULL,
  display_name text NOT NULL,
  symbol text,
  status text NOT NULL DEFAULT 'PLANNED'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_currencies PRIMARY KEY (currency_code),
  CONSTRAINT uq_currencies__numeric_code UNIQUE (numeric_code),
  CONSTRAINT ck_currencies__currency_code_format CHECK ((currency_code ~ '^[A-Z]{3}$'::text)),
  CONSTRAINT ck_currencies__display_name_not_blank CHECK ((length(btrim(display_name)) > 0)),
  CONSTRAINT ck_currencies__minor_unit_digits CHECK (((minor_unit_digits >= 0) AND (minor_unit_digits <= 4))),
  CONSTRAINT ck_currencies__numeric_code_format CHECK ((numeric_code ~ '^[0-9]{3}$'::text)),
  CONSTRAINT ck_currencies__status CHECK ((status = ANY (ARRAY['PLANNED'::text, 'ACTIVE'::text, 'INACTIVE'::text]))),
  CONSTRAINT ck_currencies__symbol_length CHECK (((symbol IS NULL) OR ((length(symbol) >= 1) AND (length(symbol) <= 8))))
);

CREATE TABLE geography.market_locales (
  market_id uuid NOT NULL,
  country_id uuid NOT NULL,
  locale text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_market_locales PRIMARY KEY (market_id, locale),
  CONSTRAINT fk_market_locales__country_locale FOREIGN KEY (country_id, locale) REFERENCES geography.country_locales(country_id, locale) ON DELETE RESTRICT,
  CONSTRAINT fk_market_locales__market_country FOREIGN KEY (market_id, country_id) REFERENCES geography.markets(market_id, country_id) ON DELETE RESTRICT
);

CREATE TABLE geography.markets (
  market_id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  country_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'PLANNED'::text,
  default_locale text NOT NULL,
  currency_code character(3) NOT NULL,
  default_time_zone_id uuid NOT NULL,
  effective_from timestamp with time zone NOT NULL,
  effective_to timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_markets PRIMARY KEY (market_id),
  CONSTRAINT uq_markets__code UNIQUE (code),
  CONSTRAINT uq_markets__market_country UNIQUE (market_id, country_id),
  CONSTRAINT fk_markets__country_id FOREIGN KEY (country_id) REFERENCES geography.countries(country_id) ON DELETE RESTRICT,
  CONSTRAINT fk_markets__country_time_zone FOREIGN KEY (country_id, default_time_zone_id) REFERENCES geography.country_time_zones(country_id, time_zone_id) ON DELETE RESTRICT,
  CONSTRAINT fk_markets__currency_code FOREIGN KEY (currency_code) REFERENCES geography.currencies(currency_code) ON DELETE RESTRICT,
  CONSTRAINT fk_markets__default_locale FOREIGN KEY (market_id, default_locale) REFERENCES geography.market_locales(market_id, locale) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT ck_markets__code_format CHECK (((code ~ '^[a-z][a-z0-9]*(-[a-z0-9]+)*$'::text) AND (length(code) <= 60))),
  CONSTRAINT ck_markets__effective_range CHECK (((effective_to IS NULL) OR (effective_to > effective_from))),
  CONSTRAINT ck_markets__name_not_blank CHECK (((length(btrim(name)) > 0) AND (length(name) <= 120))),
  CONSTRAINT ck_markets__status CHECK ((status = ANY (ARRAY['PLANNED'::text, 'ACTIVE'::text, 'INACTIVE'::text])))
);
CREATE INDEX idx_markets__active ON geography.markets USING btree (country_id, code) WHERE (status = 'ACTIVE'::text);

CREATE TABLE geography.time_zones (
  time_zone_id uuid NOT NULL DEFAULT gen_random_uuid(),
  iana_name text NOT NULL,
  status text NOT NULL DEFAULT 'PLANNED'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_time_zones PRIMARY KEY (time_zone_id),
  CONSTRAINT uq_time_zones__iana_name UNIQUE (iana_name),
  CONSTRAINT ck_time_zones__iana_name_format CHECK (((iana_name ~ '^[A-Za-z][A-Za-z0-9_+-]*(/[A-Za-z0-9_+-]+)*$'::text) AND (length(iana_name) <= 64))),
  CONSTRAINT ck_time_zones__status CHECK ((status = ANY (ARRAY['PLANNED'::text, 'ACTIVE'::text, 'INACTIVE'::text])))
);

CREATE TABLE identity.account_audit_events (
  audit_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  occurred_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  actor text NOT NULL,
  action text NOT NULL,
  account_id uuid NOT NULL,
  role_id uuid,
  changes jsonb,
  reason text,
  correlation_id text NOT NULL,
  email_contact_id uuid,
  CONSTRAINT pk_account_audit_events PRIMARY KEY (audit_event_id),
  CONSTRAINT fk_account_audit_events__account_email_contact FOREIGN KEY (account_id, email_contact_id) REFERENCES identity.email_contacts(account_id, email_contact_id) ON DELETE RESTRICT,
  CONSTRAINT fk_account_audit_events__account_id FOREIGN KEY (account_id) REFERENCES identity.accounts(account_id) ON DELETE RESTRICT,
  CONSTRAINT fk_account_audit_events__role_id FOREIGN KEY (role_id) REFERENCES identity.roles(role_id) ON DELETE RESTRICT,
  CONSTRAINT ck_account_audit_events__action CHECK ((action = ANY (ARRAY['ACCOUNT_CREATED'::text, 'EXTERNAL_IDENTITY_LINKED'::text, 'ROLE_GRANTED'::text, 'ROLE_ACTIVATED'::text, 'ROLE_DEACTIVATED'::text, 'PRIMARY_ROLE_CHANGED'::text, 'PROFILE_UPDATED'::text, 'EMAIL_ADDED'::text, 'EMAIL_CHANGE_REQUESTED'::text, 'EMAIL_VERIFICATION_REQUESTED'::text, 'EMAIL_VERIFICATION_FAILED'::text, 'EMAIL_VERIFICATION_LOCKED'::text, 'EMAIL_VERIFIED'::text, 'EMAIL_PRIMARY_CHANGED'::text]))),
  CONSTRAINT ck_account_audit_events__actor CHECK (((length(btrim(actor)) > 0) AND (length(actor) <= 200))),
  CONSTRAINT ck_account_audit_events__changes_object CHECK (((changes IS NULL) OR (jsonb_typeof(changes) = 'object'::text))),
  CONSTRAINT ck_account_audit_events__email_contact CHECK (((action ~~ 'EMAIL\_%'::text) = (email_contact_id IS NOT NULL))),
  CONSTRAINT ck_account_audit_events__role CHECK (((action ~~ 'ROLE\_%'::text) = (role_id IS NOT NULL)))
);
CREATE INDEX idx_account_audit_events__account ON identity.account_audit_events USING btree (account_id, occurred_at DESC);

CREATE TABLE identity.account_profiles (
  account_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  preferred_locale text,
  time_zone_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_account_profiles PRIMARY KEY (account_id),
  CONSTRAINT fk_account_profiles__account_id FOREIGN KEY (account_id) REFERENCES identity.accounts(account_id) ON DELETE RESTRICT,
  CONSTRAINT fk_account_profiles__preferred_locale FOREIGN KEY (preferred_locale) REFERENCES content.locales(locale) ON DELETE RESTRICT,
  CONSTRAINT fk_account_profiles__time_zone_id FOREIGN KEY (time_zone_id) REFERENCES geography.time_zones(time_zone_id) ON DELETE RESTRICT,
  CONSTRAINT ck_account_profiles__first_name CHECK ((((length(first_name) >= 1) AND (length(first_name) <= 50)) AND (first_name !~ '(^\s|\s$)'::text) AND (first_name !~ '[\u0001-\u001F\u007F-\u009F\u202A-\u202E\u2066-\u2069]'::text))),
  CONSTRAINT ck_account_profiles__last_name CHECK ((((length(last_name) >= 1) AND (length(last_name) <= 50)) AND (last_name !~ '(^\s|\s$)'::text) AND (last_name !~ '[\u0001-\u001F\u007F-\u009F\u202A-\u202E\u2066-\u2069]'::text)))
);

CREATE TABLE identity.account_roles (
  account_id uuid NOT NULL,
  role_id uuid NOT NULL,
  status text NOT NULL,
  granted_at timestamp with time zone NOT NULL DEFAULT now(),
  activated_at timestamp with time zone,
  deactivated_at timestamp with time zone,
  granted_by text NOT NULL,
  grant_source text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_account_roles PRIMARY KEY (account_id, role_id),
  CONSTRAINT fk_account_roles__account_id FOREIGN KEY (account_id) REFERENCES identity.accounts(account_id) ON DELETE RESTRICT,
  CONSTRAINT fk_account_roles__role_id FOREIGN KEY (role_id) REFERENCES identity.roles(role_id) ON DELETE RESTRICT,
  CONSTRAINT ck_account_roles__grant_source CHECK ((grant_source = ANY (ARRAY['BOOTSTRAP'::text, 'SIGNUP'::text, 'ADMIN'::text, 'SYSTEM'::text]))),
  CONSTRAINT ck_account_roles__granted_by CHECK (((length(btrim(granted_by)) > 0) AND (length(granted_by) <= 200))),
  CONSTRAINT ck_account_roles__lifecycle CHECK ((((status = 'PENDING'::text) AND (activated_at IS NULL) AND (deactivated_at IS NULL)) OR ((status = 'ACTIVE'::text) AND (activated_at IS NOT NULL) AND (deactivated_at IS NULL)) OR ((status = 'INACTIVE'::text) AND (deactivated_at IS NOT NULL)))),
  CONSTRAINT ck_account_roles__status CHECK ((status = ANY (ARRAY['PENDING'::text, 'ACTIVE'::text, 'INACTIVE'::text])))
);

CREATE TABLE identity.account_status_history (
  status_history_id uuid NOT NULL DEFAULT gen_random_uuid(),
  history_seq bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  account_id uuid NOT NULL,
  from_status text,
  to_status text NOT NULL,
  reason text,
  actor text NOT NULL,
  occurred_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  correlation_id text NOT NULL,
  CONSTRAINT pk_account_status_history PRIMARY KEY (status_history_id),
  CONSTRAINT uq_account_status_history__seq UNIQUE (history_seq),
  CONSTRAINT fk_account_status_history__account_id FOREIGN KEY (account_id) REFERENCES identity.accounts(account_id) ON DELETE RESTRICT,
  CONSTRAINT ck_account_status_history__actor CHECK (((length(btrim(actor)) > 0) AND (length(actor) <= 200))),
  CONSTRAINT ck_account_status_history__changed CHECK ((from_status IS DISTINCT FROM to_status)),
  CONSTRAINT ck_account_status_history__from_status CHECK (((from_status IS NULL) OR (from_status = ANY (ARRAY['PENDING'::text, 'ACTIVE'::text, 'SUSPENDED'::text, 'CLOSURE_REQUESTED'::text, 'CLOSED'::text])))),
  CONSTRAINT ck_account_status_history__reason CHECK (((reason IS NULL) OR ((length(btrim(reason)) > 0) AND (length(reason) <= 1000)))),
  CONSTRAINT ck_account_status_history__to_status CHECK ((to_status = ANY (ARRAY['PENDING'::text, 'ACTIVE'::text, 'SUSPENDED'::text, 'CLOSURE_REQUESTED'::text, 'CLOSED'::text])))
);
CREATE INDEX idx_account_status_history__account ON identity.account_status_history USING btree (account_id, history_seq DESC);

CREATE TABLE identity.accounts (
  account_id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL,
  primary_role_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  closed_at timestamp with time zone,
  CONSTRAINT pk_accounts PRIMARY KEY (account_id),
  CONSTRAINT fk_accounts__primary_role FOREIGN KEY (account_id, primary_role_id) REFERENCES identity.account_roles(account_id, role_id) ON DELETE RESTRICT,
  CONSTRAINT ck_accounts__closed_at CHECK (((status = 'CLOSED'::text) = (closed_at IS NOT NULL))),
  CONSTRAINT ck_accounts__status CHECK ((status = ANY (ARRAY['PENDING'::text, 'ACTIVE'::text, 'SUSPENDED'::text, 'CLOSURE_REQUESTED'::text, 'CLOSED'::text])))
);

CREATE TABLE identity.email_contacts (
  email_contact_id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  email_normalized text NOT NULL,
  status text NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  source text NOT NULL,
  verified_at timestamp with time zone,
  disabled_at timestamp with time zone,
  disabled_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_email_contacts PRIMARY KEY (email_contact_id),
  CONSTRAINT uq_email_contacts__account_contact UNIQUE (account_id, email_contact_id),
  CONSTRAINT fk_email_contacts__account_id FOREIGN KEY (account_id) REFERENCES identity.accounts(account_id) ON DELETE RESTRICT,
  CONSTRAINT ck_email_contacts__disabled CHECK ((((status = 'DISABLED'::text) = (disabled_at IS NOT NULL)) AND ((status = 'DISABLED'::text) = (disabled_reason IS NOT NULL)))),
  CONSTRAINT ck_email_contacts__disabled_reason CHECK (((disabled_reason IS NULL) OR (disabled_reason = ANY (ARRAY['REPLACED'::text, 'SUPERSEDED'::text])))),
  CONSTRAINT ck_email_contacts__email_normalized CHECK (((length(email_normalized) <= 254) AND (email_normalized ~ '^[a-z0-9!#$%&''*+/=?^_`{|}~.-]{1,64}@[a-z0-9.-]{3,253}$'::text))),
  CONSTRAINT ck_email_contacts__idp_born_verified CHECK (((source <> 'IDP_VERIFIED'::text) OR (verified_at IS NOT NULL))),
  CONSTRAINT ck_email_contacts__primary_is_verified CHECK (((NOT is_primary) OR (status = 'VERIFIED'::text))),
  CONSTRAINT ck_email_contacts__source CHECK ((source = ANY (ARRAY['USER_ENTERED'::text, 'IDP_VERIFIED'::text]))),
  CONSTRAINT ck_email_contacts__status CHECK ((status = ANY (ARRAY['PENDING'::text, 'VERIFIED'::text, 'REPLACEMENT_PENDING'::text, 'DISABLED'::text]))),
  CONSTRAINT ck_email_contacts__verified_at CHECK ((((status <> 'VERIFIED'::text) OR (verified_at IS NOT NULL)) AND ((status <> ALL (ARRAY['PENDING'::text, 'REPLACEMENT_PENDING'::text])) OR (verified_at IS NULL))))
);
CREATE UNIQUE INDEX uq_email_contacts__live_address_per_account ON identity.email_contacts USING btree (account_id, email_normalized) WHERE (status <> 'DISABLED'::text);
CREATE UNIQUE INDEX uq_email_contacts__open_per_account ON identity.email_contacts USING btree (account_id) WHERE (status = ANY (ARRAY['PENDING'::text, 'REPLACEMENT_PENDING'::text]));
CREATE UNIQUE INDEX uq_email_contacts__primary_per_account ON identity.email_contacts USING btree (account_id) WHERE is_primary;
CREATE UNIQUE INDEX uq_email_contacts__verified_address ON identity.email_contacts USING btree (email_normalized) WHERE (status = 'VERIFIED'::text);

CREATE TABLE identity.email_verification_challenges (
  challenge_id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_contact_id uuid NOT NULL,
  purpose text NOT NULL,
  code_hash text NOT NULL,
  magic_token_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used_at timestamp with time zone,
  consumed_via text,
  attempt_count integer NOT NULL DEFAULT 0,
  invalidated_at timestamp with time zone,
  invalidation_reason text,
  delivery_status text NOT NULL DEFAULT 'PENDING'::text,
  last_sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  correlation_id text NOT NULL,
  CONSTRAINT pk_email_verification_challenges PRIMARY KEY (challenge_id),
  CONSTRAINT uq_email_verification_challenges__magic_token_hash UNIQUE (magic_token_hash),
  CONSTRAINT fk_email_verification_challenges__email_contact_id FOREIGN KEY (email_contact_id) REFERENCES identity.email_contacts(email_contact_id) ON DELETE RESTRICT,
  CONSTRAINT ck_email_verification_challenges__attempts CHECK ((attempt_count >= 0)),
  CONSTRAINT ck_email_verification_challenges__closed_once CHECK (((used_at IS NULL) OR (invalidated_at IS NULL))),
  CONSTRAINT ck_email_verification_challenges__code_hash CHECK ((code_hash ~ '^[0-9a-f]{64}$'::text)),
  CONSTRAINT ck_email_verification_challenges__consumed CHECK ((((used_at IS NULL) = (consumed_via IS NULL)) AND ((consumed_via IS NULL) OR (consumed_via = ANY (ARRAY['CODE'::text, 'LINK'::text]))))),
  CONSTRAINT ck_email_verification_challenges__correlation CHECK (((length(btrim(correlation_id)) > 0) AND (length(correlation_id) <= 200))),
  CONSTRAINT ck_email_verification_challenges__delivery CHECK (((delivery_status = ANY (ARRAY['PENDING'::text, 'SENT'::text, 'FAILED'::text])) AND ((delivery_status = 'SENT'::text) = (last_sent_at IS NOT NULL)))),
  CONSTRAINT ck_email_verification_challenges__expiry CHECK ((expires_at > created_at)),
  CONSTRAINT ck_email_verification_challenges__invalidated CHECK ((((invalidated_at IS NULL) = (invalidation_reason IS NULL)) AND ((invalidation_reason IS NULL) OR (invalidation_reason = ANY (ARRAY['SUPERSEDED'::text, 'LOCKED'::text, 'CONTACT_DISABLED'::text, 'DELIVERY_FAILED'::text]))))),
  CONSTRAINT ck_email_verification_challenges__magic_token_hash CHECK ((magic_token_hash ~ '^[0-9a-f]{64}$'::text)),
  CONSTRAINT ck_email_verification_challenges__purpose CHECK ((purpose = ANY (ARRAY['INITIAL_EMAIL'::text, 'CHANGE_EMAIL'::text])))
);
CREATE INDEX idx_email_verification_challenges__contact_created ON identity.email_verification_challenges USING btree (email_contact_id, created_at DESC);
CREATE UNIQUE INDEX uq_email_verification_challenges__open_per_contact ON identity.email_verification_challenges USING btree (email_contact_id) WHERE ((used_at IS NULL) AND (invalidated_at IS NULL));

CREATE TABLE identity.external_identities (
  external_identity_id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  provider_type text NOT NULL,
  issuer text NOT NULL,
  provider_subject text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_external_identities PRIMARY KEY (external_identity_id),
  CONSTRAINT uq_external_identities__provider_issuer_subject UNIQUE (provider_type, issuer, provider_subject),
  CONSTRAINT fk_external_identities__account_id FOREIGN KEY (account_id) REFERENCES identity.accounts(account_id) ON DELETE RESTRICT,
  CONSTRAINT ck_external_identities__issuer CHECK (((length(btrim(issuer)) > 0) AND (length(issuer) <= 512) AND (issuer !~ '[\u0001-\u001F\u007F]'::text))),
  CONSTRAINT ck_external_identities__provider_type CHECK ((provider_type = 'KEYCLOAK'::text)),
  CONSTRAINT ck_external_identities__subject CHECK (((length(btrim(provider_subject)) > 0) AND (length(provider_subject) <= 255) AND (provider_subject !~ '[\u0001-\u001F\u007F]'::text)))
);

CREATE TABLE identity.roles (
  role_id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name_content_key text NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pk_roles PRIMARY KEY (role_id),
  CONSTRAINT uq_roles__code UNIQUE (code),
  CONSTRAINT fk_roles__name_content_key FOREIGN KEY (name_content_key) REFERENCES content.entries(key) ON DELETE RESTRICT,
  CONSTRAINT ck_roles__code_format CHECK ((code ~ '^[A-Z][A-Z0-9_]{1,29}$'::text)),
  CONSTRAINT ck_roles__name_content_key_format CHECK ((name_content_key ~ '^[a-z][a-z0-9_]*([.][a-z][a-z0-9_]*)+$'::text)),
  CONSTRAINT ck_roles__status CHECK ((status = ANY (ARRAY['ACTIVE'::text, 'INACTIVE'::text])))
);

CREATE TABLE integration.outbox_events (
  outbox_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  aggregate_type text NOT NULL,
  aggregate_id text NOT NULL,
  event_type text NOT NULL,
  event_version integer NOT NULL,
  actor_type text NOT NULL,
  actor_id text,
  payload_json jsonb NOT NULL,
  correlation_id text NOT NULL,
  causation_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  next_attempt_at timestamp with time zone NOT NULL DEFAULT now(),
  published_at timestamp with time zone,
  publish_attempts integer NOT NULL DEFAULT 0,
  last_error text,
  CONSTRAINT pk_outbox_events PRIMARY KEY (outbox_event_id),
  CONSTRAINT ck_outbox_events__actor_type CHECK ((actor_type = ANY (ARRAY['user'::text, 'system'::text, 'service'::text]))),
  CONSTRAINT ck_outbox_events__attempts_nonnegative CHECK ((publish_attempts >= 0)),
  CONSTRAINT ck_outbox_events__event_type_format CHECK ((event_type ~ '^bananagig[.][a-z][a-z0-9-]*[.][a-z][a-z0-9-]*[.]v[1-9][0-9]*$'::text)),
  CONSTRAINT ck_outbox_events__event_version_positive CHECK ((event_version > 0)),
  CONSTRAINT ck_outbox_events__payload_is_object CHECK ((jsonb_typeof(payload_json) = 'object'::text)),
  CONSTRAINT ck_outbox_events__published_has_attempt CHECK (((published_at IS NULL) OR (publish_attempts >= 1))),
  CONSTRAINT ck_outbox_events__version_matches_type CHECK (("right"(event_type, (length((event_version)::text) + 2)) = ('.v'::text || (event_version)::text)))
);
CREATE INDEX idx_outbox_events__pending ON integration.outbox_events USING btree (next_attempt_at, created_at) WHERE (published_at IS NULL);
CREATE INDEX idx_outbox_events__published_at ON integration.outbox_events USING btree (published_at) WHERE (published_at IS NOT NULL);

CREATE TABLE public.schema_migrations (
  filename text NOT NULL,
  checksum text NOT NULL,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  version integer NOT NULL,
  duration_ms integer,
  CONSTRAINT pk_schema_migrations PRIMARY KEY (version),
  CONSTRAINT uq_schema_migrations__filename UNIQUE (filename),
  CONSTRAINT ck_schema_migrations__duration_ms_nonnegative CHECK (((duration_ms IS NULL) OR (duration_ms >= 0))),
  CONSTRAINT ck_schema_migrations__filename_matches_version CHECK ((filename ~ (('^'::text || lpad((version)::text, 4, '0'::text)) || '_[a-z0-9_]+[.]sql$'::text))),
  CONSTRAINT ck_schema_migrations__version_positive CHECK ((version > 0))
);
